import React, { useState } from 'react';
import { generateHobbyImage } from '../services/geminiService';
import { Loader2, Camera, Trophy } from 'lucide-react';

const HobbyGallery: React.FC = () => {
  const [activeSport, setActiveSport] = useState<'Basketball' | 'Badminton' | null>(null);
  const [images, setImages] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);

  const handleGenerate = async (sport: 'Basketball' | 'Badminton') => {
    setActiveSport(sport);
    setLoading(true);
    try {
      const result = await generateHobbyImage(sport);
      setImages(prev => ({ ...prev, [sport]: result }));
    } catch (e) {
      console.error(e);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="w-full h-full flex flex-col p-8 relative overflow-hidden group">
      {/* Background Texture */}
      <div className="absolute inset-0 opacity-10 bg-[radial-gradient(circle_at_center,_var(--tw-gradient-stops))] from-neutral-500 to-transparent pointer-events-none"></div>

      <div className="relative z-10 mb-6">
        <h3 className="font-serif text-3xl mb-2">Off the Court</h3>
        <p className="font-mono text-xs uppercase tracking-widest text-neutral-400">
          Athlete // Lifestyle
        </p>
      </div>

      <div className="relative z-10 flex gap-2 mb-6">
        <button 
          onClick={() => handleGenerate('Basketball')}
          disabled={loading}
          className={`flex-1 py-3 border border-paper/30 font-mono text-[10px] md:text-xs uppercase font-bold hover:bg-paper hover:text-ink transition-all ${activeSport === 'Basketball' ? 'bg-paper text-ink' : ''}`}
        >
          Basketball
        </button>
        <button 
          onClick={() => handleGenerate('Badminton')}
          disabled={loading}
          className={`flex-1 py-3 border border-paper/30 font-mono text-[10px] md:text-xs uppercase font-bold hover:bg-paper hover:text-ink transition-all ${activeSport === 'Badminton' ? 'bg-paper text-ink' : ''}`}
        >
          Badminton
        </button>
      </div>

      <div className="flex-1 w-full border border-neutral-800 bg-neutral-900/50 relative overflow-hidden min-h-[200px]">
        {loading ? (
           <div className="absolute inset-0 flex flex-col items-center justify-center">
              <Loader2 className="w-6 h-6 animate-spin mb-2 text-swiss-red" />
              <div className="font-mono text-[10px] animate-pulse">GENERATING 8K VISUAL...</div>
           </div>
        ) : activeSport && images[activeSport] ? (
           <div className="absolute inset-0 w-full h-full animate-in fade-in duration-700">
              <img src={images[activeSport]} alt={activeSport} className="w-full h-full object-cover opacity-90 hover:opacity-100 transition-opacity" />
              <div className="absolute bottom-2 right-2 bg-black/50 backdrop-blur px-2 py-1 border border-white/10">
                 <p className="font-mono text-[9px] text-white">GEMINI_3_PRO</p>
              </div>
           </div>
        ) : (
           <div className="absolute inset-0 flex flex-col items-center justify-center opacity-30">
              <Trophy className="w-12 h-12 mb-2" />
              <p className="font-mono text-[10px]">SELECT SPORT</p>
           </div>
        )}
      </div>
      
      <div className="mt-4 font-mono text-[9px] text-neutral-500 z-10 text-right">
         * Visuals generated by Gemini 3 Pro
      </div>
    </div>
  );
};

export default HobbyGallery;